version: '3'
services:
  juiceshop.local:
    image: bkimminich/juice-shop:v12.1.0
  repeater:
    image: neuralegion/repeater:latest
    restart: always
    environment:
      REPEATER_TOKEN: ${NEXPLOIT_TOKEN}
      REPEATER_AGENT: ${REPEATER}
      DEBUG: nexploit-cli
