name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  start_and_wait_scan:
    runs-on: ubuntu-latest
    name: A job to run a Nexploit scan
    steps:
      - uses: actions/checkout@v2
      - run: |
          sudo apt update
          sudo curl -L "https://github.com/docker/compose/releases/download/1.26.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          sudo apt-get install nodejs npm
          sudo npm install -g @neuralegion/nexploit-cli
      - name: Docker-Compose
        run: |
          sudo docker-compose up -d
      - run: sleep 10s
      - name: Start Nexploit Scan 🏁
        id: start
        run: |
          SCAN_ID=$(nexploit-cli scan:run --name Juice-Shop --crawler http://juiceshop.local --repeater 1f7493f3-0233-4ac4-a4b9-9a7273f4fcae --token ${{ secrets.NEXPLOIT_TOKEN }})
          echo $SCAN_ID
          echo "::set-env name=SCAN_ID::$SCAN_ID"
      - name: Get the output scan url
        run: echo "Scan was started with ID ${{ env.SCAN_ID }}"
      - name: Wait for issues
        run: nexploit-cli scan:polling --interval 30s --timeout 10m --token ${{ secrets.NEXPLOIT_TOKEN }} --breakpoint high_issue ${{ env.SCAN_ID }}
      - name: Stop Scan
        if: ${{ always() }}
        run: nexploit-cli scan:stop --token ${{ secrets.NEXPLOIT_TOKEN }} ${{ env.SCAN_ID }}
