name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  start_and_wait_scan:
    runs-on: ubuntu-latest
    name: A job to run a Nexploit scan
    steps:
      - uses: actions/checkout@v2
      - run: |
          sudo apt update
          sudo curl -L "https://github.com/docker/compose/releases/download/1.26.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          sudo apt-get install nodejs npm
          sudo npm install -g @neuralegion/nexploit-cli
      - name: Docker-Compose
        run: |
          sudo docker-compose up -d
      - run: sleep 10s
      - name: Start Nexploit Scan 🏁
        id: start
        run: |
          SCAN_ID=$(nexploit-cli scan:run --name Juice-Shop --crawler https://juice-shop.herokuapp.com --token ${{ secrets.NEXPLOIT_TOKEN }})
          echo $SCAN_ID
          echo "::set-env name=scan_id::$SCAN_ID"
      - name: Get the output scan url
        run: echo ${{ steps.start.outputs.scan_id }}
      - name: Wait for issues
        run: nexploit-cli scan:polling --token ${{ secrets.NEXPLOIT_TOKEN }} --breakpoint high_issue --interval 3000 --timeout 1h ${{ steps.start.outputs.scan_id }}
